<?php

namespace ContainerGHoZoZf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZgBsslSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZgBsslS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZgBsslS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\TicketController::create' => ['privates', '.service_locator.Km2KOcc', 'get_ServiceLocator_Km2KOccService', true],
            'App\\Controller\\TicketController::list' => ['privates', '.service_locator.Km2KOcc', 'get_ServiceLocator_Km2KOccService', true],
            'App\\Controller\\TicketController::update' => ['privates', '.service_locator.Km2KOcc', 'get_ServiceLocator_Km2KOccService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\TicketController:create' => ['privates', '.service_locator.Km2KOcc', 'get_ServiceLocator_Km2KOccService', true],
            'App\\Controller\\TicketController:list' => ['privates', '.service_locator.Km2KOcc', 'get_ServiceLocator_Km2KOccService', true],
            'App\\Controller\\TicketController:update' => ['privates', '.service_locator.Km2KOcc', 'get_ServiceLocator_Km2KOccService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\TicketController::create' => '?',
            'App\\Controller\\TicketController::list' => '?',
            'App\\Controller\\TicketController::update' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\TicketController:create' => '?',
            'App\\Controller\\TicketController:list' => '?',
            'App\\Controller\\TicketController:update' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
